### PR TITLE
dstor: addresses a dstor compatibility issues

### LINKED ISSUE #563: v2.x to v1.2 dstore cross-version compatibility not working
The way to test this is:

* build OMPI master - you can build it with shared libraries

* build OMPI v2.x with --enable-static --disable-shared, and then compile the hello_c example

* Set your paths to point to OMPI master installation

* Change to the OMPI v2.x example directory

* execute "mpirun -n 1 ./hello_c"

The example hello_c program will segfault in the dstore fetch routine:
```
[rhc001:116746] PMIx_client initialized
[rhc001:116746] [[31196,1],0][ess_pmi_module.c:141] MODEX RECV VALUE FOR PROC [[31196,1],0] KEY pmix.lrank
[rhc001:116746] [[31196,1],0] PMIx_client get on proc [[31196,1],0] key pmix.lrank
[rhc001:116746] pmix: get_nb value for proc 2044461057:0 key pmix.lrank
[rhc001:116746] pmix: getnbfn value for proc 2044461057:0 key pmix.lrank
[rhc001:116746] HASH:FETCH rank 0 key pmix.lrank
[rhc001:116746] HASH:FETCH proc data for rank 0 not found
[rhc001:116746] src/dstore/pmix_esh.c:1189:_esh_fetch: for 2044461057:2147483646 look for key pmix.lrank
[rhc001:116746] src/dstore/pmix_esh.c:1870:_update_initial_segment_info
[rhc001:116746] src/dstore/pmix_esh.c:1894:_get_ns_info_from_initial_segment
[rhc001:116746] src/dstore/pmix_esh.c:1925:_get_track_elem_for_namespace: nspace 2044461057
[rhc001:116746] src/dstore/pmix_esh.c:1728:_update_ns_elem
[rhc001:116746] src/dstore/pmix_esh.c:1687:_attach_new_segment: segment type 1, nspace 2044461057, id 0
[rhc001:116746] src/dstore/pmix_esh.c:1687:_attach_new_segment: segment type 2, nspace 2044461057, id 0
[rhc001:116746] src/dstore/pmix_esh.c:1962:_get_rank_meta_info
[rhc001:116746] src/dstore/pmix_esh.c:2108:_get_data_region_by_offset
[rhc001:116746] src/dstore/pmix_esh.c:1367:_esh_fetch: for rank 2044461057:2147483646, skip key B look for key pmix.lrank
[rhc001:116746] *** Process received signal ***
[rhc001:116746] Signal: Segmentation fault (11)
[rhc001:116746] Signal code:  (128)
[rhc001:116746] Failing at address: (nil)
[rhc001:116746] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x7f043eddc5e0]
[rhc001:116746] [ 1] /lib64/libc.so.6(+0x135e67)[0x7f043eb3fe67]
[rhc001:116746] [ 2] ./hello[0x7bcd9a]
[rhc001:116746] [ 3] ./hello[0x7b97d0]
[rhc001:116746] [ 4] ./hello[0x7e6d52]
[rhc001:116746] [ 5] ./hello[0x72fc78]
[rhc001:116746] [ 6] ./hello[0x7c6534]
[rhc001:116746] [ 7] /lib64/libpthread.so.0(+0x7e25)[0x7f043edd4e25]
[rhc001:116746] [ 8] /lib64/libc.so.6(clone+0x6d)[0x7f043eb0234d]
[rhc001:116746] *** End of error message ***

(gdb) where
#0  0x00007f043eb3fe67 in __strncmp_sse42 () from /lib64/libc.so.6
#1  0x00000000007bcd9a in _esh_fetch (nspace=0x1912568 "2044461057", rank=2147483646, key=0x86c1fe "pmix.lrank", kvs=0x7f043d09bbc0) at src/dstore/pmix_esh.c:1309
#2  0x00000000007b97d0 in pmix_dstore_fetch (nspace=0x1912568 "2044461057", rank=2147483646, key=0x86c1fe "pmix.lrank", kvs=0x7f043d09bbc0) at src/dstore/pmix_dstore.c:74
#3  0x00000000007e6d52 in _getnbfn (fd=-1, flags=4, cbdata=0x1938af0) at src/client/pmix_client_get.c:562
#4  0x000000000072fc78 in event_process_active_single_queue (activeq=0x1936410, base=0x1936430) at event.c:1370
#5  event_process_active (base=<optimized out>) at event.c:1440
#6  opal_libevent2022_event_base_loop (base=0x1936430, flags=1) at event.c:1644
#7  0x00000000007c6534 in progress_engine (obj=0x1936430) at src/util/progress_threads.c:52
#8  0x00007f043edd4e25 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f043eb0234d in clone () from /lib64/libc.so.6
(gdb) up
#1  0x00000000007bcd9a in _esh_fetch (nspace=0x1912568 "2044461057", rank=2147483646, key=0x86c1fe "pmix.lrank", kvs=0x7f043d09bbc0) at src/dstore/pmix_esh.c:1309
1309	            if (0 == strncmp(ESH_KNAME_PTR(addr), ESH_REGION_INVALIDATED, ESH_KNAME_LEN(ESH_REGION_INVALIDATED))) {
(gdb) print addr
$1 = (uint8_t *) 0x6d707f0437800012 <Address 0x6d707f0437800012 out of bounds>
```
I see that the bfrops support in OMPI master is missing some backward types, and so this might be caused by that problem. For now, I'm just tracking this here.

At some point, we really should address this pack/unpack issue in dstore as it will continue to cause us problems going forward.

### PR DESCRIPTION
**Pull request by karasevb**
Fixed dstor compatibility issues between v1.2 and v2.x.

Fixes #563

Note: the `dstor` cannot support multi-clients case for nspace when clients in the same one nspace will be has different versions, i.e. in one nspace should be use clients v1.2 only, or v2.x only.

### CODE REVIEW

File: src/mca/gds/ds12/gds_dstore.c [hunk 1]
```diff
@@ -63,60 +63,216 @@
 #define ESH_KV_SIZE(addr)                                   \
 __extension__ ({                                            \
     size_t sz;                                              \
-    memcpy(&sz, addr, sizeof(size_t));                      \
+    if (PMIX_PROC_IS_V1(_client_peer())) {                  \
```
Comment (artpol84) [inline src/mca/gds/ds12/gds_dstore.c]: @karasevb We discussed that those will be a function pointers to avoid extra "ifs" all around the code. Please fix.

**Comment by artpol84** [comment]
@rhc54 I would like to have the option to review before the merge.
@karasevb asked for that and I was going to do that today. Please wait for my approval next time.

**Comment by rhc54** [comment]
Sorry, I didn't see that there were two requests.

**Comment by artpol84** [comment]
Yeah, no problem. Looks like we may do some minor change in the code. Will pr separately.

**Comment by rhc54** [comment]
thanks - I'll try to look more closely next time
