### PR TITLE
Flexible integer packing with `psquash` framework in `bfrops` v4

### LINKED ISSUE #681: Modex size analysis
## Short description
This Issue is to track the analysis of the modex size and searching for the ways to optimize it.
For the reference: https://github.com/open-mpi/ompi/pull/4826

## First measurements
The first observation is to clarify on @rhc54 [comment](https://github.com/open-mpi/ompi/pull/4826#issuecomment-366464181) about the effect of extra information that is being packed when PMIx is configured with `--enable-debug`.

I went back and double-checked our build and indeed `--enable-debug` was there. So here are some details. Details on how to reproduce below.

`--disable-debug`:
```
[jazz06:34916] recvd FENCE
[jazz06:34916] recvd fence from 1110704129:1 with 1 procs
[jazz06:34916] fence complete
[jazz06:34916] fence - assembling data: 5
[jazz06:34916] rank_info: rank=1, size = 23
[jazz06:34916] rank_data: rank=1, size = 143
[jazz06:34916] commit_message: rank=1 added, size = 162 # (162 - 143 - 5 = 14)
[jazz06:34916] commit_message: final size = 176          # (176 - 62 = 14)
```
`--enable-debug`
```
[jazz09:167487] recvd FENCE
[jazz09:167487] recvd fence from 1440743425:0 with 1 procs
[jazz09:167487] fence complete
[jazz09:167487] fence - assembling data: 9                 # (9 - 5 = 4)
[jazz09:167487] rank_info: rank=0, size = 27               # (27 - 23 = 4)
[jazz09:167487] rank_data: rank=0, size = 156              # (156 - 143 = 13)
[jazz09:167487] commit_message: rank=0 added, size = 183   # (183 - 9 - 156 = 18; 18 - 14 = 4)
[jazz09:167487] commit_message: final size = 201           # (201 - 176 = 25, 25 - 4 - 4 - 13 - 4 = 0 )
```
## Analysis
* Indeed debugging flag adds ~25B on top of the modex size (12%)
* Release version size is 176B which is still high
* In the rank contribution (release) 23B are taken by the rank identification (`rank_info`: 23B/176B = 13%). And this will be the case for each additional rank. Reasonable optimization here would be (as @rhc54 [suggested](https://github.com/open-mpi/ompi/pull/4826#issuecomment-366466299)) is to "cite" namespace only once and then only provide rank number. In case of multiple namespace we will need to group ranks by namespace.
The issue here is that once this is at the RM side there is no way to reduce it further (as namespaces will be duplicated in messages from different nodes. On the other hand this will only be an issue for the tree-based modex implementations that are not very efficient for the modex exchange.
* Knowing that UCX endpoint size was ~50B in this particular run we observe that `rank-data` field is also too large and equal to 120B (143B - 23B; (120B-50B) / 120B = 58%). I'm going to investigate that further.
* Finally some sort of "footer" is being applied to the buffer twice:
  * once in `commit_message: rank=1 added`
  * once when packing the final buffer: `commit_message: final size`
As the first "footer" is per rank it contributes 14/176 = 8% to the modex size.

## Reproduction 
The following patch was applied to the built-in PMIx in OMPI https://github.com/open-mpi/ompi/commit/b6e825f83ebf34003dda922cd3f9237d10571312:
```patch
diff --git a/opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c b/opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c                                                                                                                  
index 29fb193..c773db4 100644                                                                                                                                                                                                                 
--- a/opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c                                                                                                                                                                                  
+++ b/opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c                                                                                                                                                                                  
@@ -614,7 +614,7 @@ pmix_status_t pmix_server_fence(pmix_server_caddy_t *cd,                                                                                                                                                                  
.                                                                                                                                                                                                                                             
         if (PMIX_COLLECT_YES == trk->collect_type) {                                                                                                                                                                                         
             pmix_output_verbose(2, pmix_globals.debug_output,                                                                                                                                                                                
-                                "fence - assembling data");                                                                                                                                                                                  
+                                "fence - assembling data: %u", (unsigned int) bucket.bytes_used);                                                                                                                                            
             PMIX_LIST_FOREACH(scd, &trk->local_cbs, pmix_server_caddy_t) {                                                                                                                                                                   
                 /* get any remote contribution - note that there                                                                                                                                                                             
                  * may not be a contribution */                                                                                                                                                                                              
@@ -635,6 +635,9 @@ pmix_status_t pmix_server_fence(pmix_server_caddy_t *cd,                                                                                                                                                                  
                         PMIX_DESTRUCT(&cb);                                                                                                                                                                                                  
                         goto cleanup;                                                                                                                                                                                                        
                     }                                                                                                                                                                                                                        
+                    pmix_output_verbose(2, pmix_globals.debug_output,                                                                                                                                                                        
+                                "rank_info: rank=%d, size = %u", pcs.rank , (unsigned int) pbkt.bytes_used);                                                                                                                                 
+                                                                                                                                                                                                                                             
                     /* pack the returned kval's */                                                                                                                                                                                           
                     PMIX_LIST_FOREACH(kv, &cb.kvs, pmix_kval_t) {                                                                                                                                                                            
                         PMIX_BFROPS_PACK(rc, pmix_globals.mypeer, &pbkt, kv, 1, PMIX_KVAL);                                                                                                                                                  
@@ -644,12 +647,19 @@ pmix_status_t pmix_server_fence(pmix_server_caddy_t *cd,                                                                                                                                                                
                             goto cleanup;                                                                                                                                                                                                    
                         }                                                                                                                                                                                                                    
                     }                                                                                                                                                                                                                        
+                                                                                                                                                                                                                                             
+                    pmix_output_verbose(2, pmix_globals.debug_output,                                                                                                                                                                        
+                                "rank_data: rank=%d, size = %u", pcs.rank , (unsigned int) pbkt.bytes_used);                                                                                                                                 
+                                                                                                                                                                                                                                             
                     /* extract the blob */                                                                                                                                                                                                   
                     PMIX_UNLOAD_BUFFER(&pbkt, bo.bytes, bo.size);                                                                                                                                                                            
                     PMIX_DESTRUCT(&pbkt);                                                                                                                                                                                                    
                     /* pack the returned blob */                                                                                                                                                                                             
                     PMIX_BFROPS_PACK(rc, pmix_globals.mypeer, &bucket,                                                                                                                                                                       
                                      &bo, 1, PMIX_BYTE_OBJECT);                                                                                                                                                                              
+                    pmix_output_verbose(2, pmix_globals.debug_output,                                                                                                                                                                        
+                                "commit_message: rank=%d added, size = %u", pcs.rank , (unsigned int) bucket.bytes_used);                                                                                                                    
+                                                                                                                                                                                                                                             
                     PMIX_BYTE_OBJECT_DESTRUCT(&bo);                                                                                                                                                                                          
                     if (PMIX_SUCCESS != rc) {                                                                                                                                                                                                
                         PMIX_ERROR_LOG(rc);                                                                                                                                                                                                  
@@ -677,6 +687,10 @@ pmix_status_t pmix_server_fence(pmix_server_caddy_t *cd,                                                                                                                                                                 
         /* now unload the blob and pass it upstairs */                                                                                                                                                                                       
         PMIX_UNLOAD_BUFFER(&bucket, data, sz);                                                                                                                                                                                               
         PMIX_DESTRUCT(&bucket);                                                                                                                                                                                                              
+                                                                                                                                                                                                                                             
+        pmix_output_verbose(2, pmix_globals.debug_output,                                                                                                                                                                                    
+                                "commit_message: final size = %u", sz);                                                                                                                                                                      
+                                                                                                                                                                                                                                             
         pmix_host_server.fence_nb(trk->pcs, trk->npcs,                                                                                                                                                                                       
                                   trk->info, trk->ninfo,                                                                                                                                                                                     
                                   data, sz, trk->modexcbfunc, trk);                 
```

Command line (2-node allocation):
```shell
$ mpirun -n 2 --debug-daemons --map-by node -mca btl self -mca pmix_base_verbose 2 -mca coll ^hcoll \
    -mca pml ucx --report-bindings -x UCX_TLS=dc -x UCX_NET_DEVICES=mlx5_0:1 \
    ./ring_c 2>&1 | tee -a tmp.data
```

### PR DESCRIPTION
**Pull request by karasevb**
- Introduced the new `psquash` framework (Thanks @jjhursey: https://github.com/pmix/pmix/issues/681#issuecomment-472149066)
- Added flexible packing for `psquash:flex128` component (Thanks @artpol84: https://github.com/pmix/pmix/pull/1130#issuecomment-470141719)
- `psquash:native`  component implements the native `bfrops` integer packing functions.
- `bfrops` v4 uses `psquash` framework for integer packing.

Refs #1130 
Closes #681

### CODE REVIEW

**Comment by karasevb** [comment]
bot:retest

**Comment by rhc54** [comment]
Sorry about the errant review - it was posted in the incorrect window 😦

**Comment by artpol84** [comment]
@rhc5;
I’m not sure I understand how flex256 hurts here. 
One of the important use of it is to eliminate extra 0s in the service information. We do not intend to touch user data.
So it is not clear to me why you need to disable it for some jobs.
Can you elaborate?

**Comment by artpol84** [comment]
To re-iterate: UCX endpoint is a blob and all we need from this PR is to reduce the amount of service information that is going to be the same for all jobs/namespaces.

**Comment by rhc54** [comment]
I'm afraid I don't know what you mean by "service information". The only thing in OMPI's modex is endpoint info. Can you clarify?

Either way, I think you may have missed my point. We need to step away from thinking of "modex" in terms of how OMPI uses it, or even how MPI does. Other programming models may well exchange information of a completely different nature than what we do. We need to respect that possibility and provide flexibility where possible.

In this case, as with the modex key-table, it isn't that hard for us to do so. It means we need a multi-select framework (which we have multiple examples of already in PMIx) and an attribute indicating which component this particular job/nspace wishes to use. This is pretty simple to provide and leaves open the option for other environments to still use PMIx according to their own preferences.

**Comment by rhc54** [comment]
Actually, I think we can implement this even more simply by utilizing the PMIX_COLLECTIVE_ALGO attribute. You could pass that into the specific fence operation, giving it a value that indicates you want flex256 encoding for this particular fence. This way you could contain tracking of the psquash component to the fence tracker object instead of having to include it in the client connection protocol.

**Comment by artpol84** [comment]
> I'm afraid I don't know what you mean by "service information". The only thing in OMPI's modex is endpoint info. Can you clarify?

Service information is the meta information that bfrops is introducing to describe user data.
I think you are missing what I’m trying to say as well.

Can you provide an exact concern about flexible packing? In what cases it will not work?

**Comment by artpol84** [comment]
> Other programming models may well exchange information of a completely different nature than what we do. We need to respect that possibility and provide flexibility where possible.

Bfrops meta information will be the same regardless.

**Comment by artpol84** [comment]
Flexible encoding does not break things so your concern about possible ephemeral programming model seems to be to weak to enforce additional amount of work that will be on us.
As we don’t break anything and benefit existing use cases I think we can defer solving this to a time when the modex size problem will be encountered (if it ever will, though I doubt that)

**Comment by rhc54** [comment]
Okay, you are now starting to finally communicate what I originally asked: what are you trying to accomplish. It now appears that it is not reduction of the modex data itself, but instead compaction of the bfrops description information. In the case of an optimized system, that consists of the number of items being stored for each entry - the data type is not stored in such cases. So we apparently are talking about a different way to encode an int32 that describes how many elements of this type were stored. Is that what you are proposing here?

It would have been helpful to have that clarified earlier in this thread, but that is now a separate issue. I'll give some thought as to what that might mean now that we have some clarity as to the target. I'm puzzled by your last comment, however - if the modex size problem doesn't yet exist, then why are we even talking about this?

Please understand: you may not recognize or understand uses beyond OMPI - but that doesn't mean they don't exist or deserve equal respect. Checking the fence call to see if a collective algo was specified and then using the plugin it directs is a pretty minimal change. Sadly, we are likely to spend more time arguing about it than implementation requires. Going forward, we need to become more sensitive to hard-coding OMPI optimizations and recognize that other models/uses need to be considered, even if it means extra work to ensure adequate flexibility exists.

**Comment by artpol84** [comment]
> Okay, you are now starting to finally communicate what I originally asked: what are you trying to accomplish. It now appears that it is not reduction of the modex data itself, but instead compaction of the bfrops description information. In the case of an optimized system, that consists of the number of items being stored for each entry - the data type is not stored in such cases. So we apparently are talking about a different way to encode an int32 that describes how many elements of this type were stored. Is that what you are proposing here?

This is very disappointing to hear that "I'm only now starting to communicate". I was explaining this in a very detailed level for a couple of months. Please see my main (most detailed comments).
* https://github.com/pmix/pmix/issues/681#issuecomment-367920982
* https://github.com/pmix/pmix/issues/681#issuecomment-368249149
* https://github.com/pmix/pmix/issues/681#issuecomment-455986873
* https://github.com/pmix/pmix/pull/1130#issuecomment-470339443

It is hard to build an efficient discussion when the other side is not carefully following the responses.
Maybe it is better to discuss this over the phone.

> Checking the fence call to see if a collective algo was specified and then using the plugin it directs is a pretty minimal change. Sadly, we are likely to spend more time arguing about it than implementation requires. Going forward, we need to become more sensitive to hard-coding OMPI optimizations and recognize that other models/uses need to be considered, even if it means extra work to ensure adequate flexibility exists.

I disagree that this is a minor thing. This has an implication on the usage of this feature. Basically, as you describe, it will be disabled by default. While I believe that in most common cases it will be beneficial.

**Comment by jjhursey** [comment]
It is unfortunate that we all have been talking past each other on this topic. I must admit that it did take me a while to understand that this is focused on the bfrops data structure surrounding each rank's modex blob and not the blob itself. I'm happy that we have reached an understanding of the intention of this PR.

Now that I'm seeing the code change and the discussion around it, I'm wondering (again) if a framework is really necessary for this if it is only going to be used by the bfops framework. I still want the ability to enable/disable this at runtime. But could that best be done with an MCA parameter instead of a full framework?

I'm not suggesting another implementation - you all have put in a lot of effort into two versions of this already. Just a bit more discussion. We should definitely talk about this PR and PR #1149 on the teleconf this week.

I'd have to think if we want to enable/disable this per-namespace or not. Since it's hidden from the end user I'm leaning towards not - leaving it globally on or off.

**Comment by artpol84** [comment]
@jjhursey note, though we are targeting service information, this change affects all bfrop packing functionality.
This means that if a user is using PMIx data types he will be influenced by this change as well (which is not necessarily bad IMO).

@rhc54's point was that flex packing doesn't help if user provides a blob. This is not correct because bfrops service information is still being compressed.

**Comment by jjhursey** [comment]
Per teleconf (March 21):
 * Adding the framework did help make the code cleaner/clearer so it is good to keep (vs an MCA parameter), and the framework clearly separates this activity from that of the broader bfrops framework activity. So from a code clarity stance, a framework here is a good thing to do.
 * We can merge this in without the compression extension to the `psquash` framework. @jjhursey will investigate that as a separate activity - no need to hold up this PR.
 * @rhc54 's earlier review seems to have been addressed by the later conversation clarifying that this optimization focuses on the data structure around the modex (and maybe the modex content if it uses integers). I've dismissed the earlier review to prevent holding this change for that reason. If there are other reasons to hold this PR please re-review.
 * The WIP flag is still on this PR - @karasevb are there more changes needed for this PR before final review?
 * If there are no objections to this PR then I think we can do the final review and, barring any issues, merge to `master`.

File: src/mca/psquash/base/base.h [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+/**
+ * Sizeof by PMIx type integer values.
+ *
+ * r - return status code
+ * t - type (pmix_data_type_t) of integer value
+ * s - size of type in bytes
+ * (see a comment to `pmix_bfrops_pack_flex` for additional details)
+ */
+#define PMIX_SQUASH_TYPE_SIZEOF(r, t, s)                    \
```
Comment (jjhursey) [inline src/mca/psquash/base/base.h]: Question: Should this macro be part of `bfrops` instead of `psquash`?

I originally put it here since the flex component was the primary user, but looking at it now I think it might be better associated with `bfrops`. I'm fine either way.

File: src/mca/psquash/psquash.h [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+typedef pmix_status_t (*pmix_psquash_decode_int_fn_t) (pmix_data_type_t type,
+                                                       void *src, size_t src_len,
+                                                       void *dest, size_t *dst_len);
+
+/**
+ * Base structure for a PSQUASH module
+ */
+typedef struct {
+    const char *name;
+    /* flag of necessity to pack the type of value */
```
Comment (jjhursey) [inline src/mca/psquash/psquash.h]: I don't understand what this flag is communicating. From the bfrops code I _think_ it means this.
```suggestion
    /* flag indicating if the type is encoded within the value, otherwise, it is necessary to further pack the type with the value. */
```
Is this rewording accurate?

If so then `flex128` has `int_type_is_encoded=false` and `native` has it set to `true`. And it's only when it's `true` that the `bfrops` component encodes the type. That seems to be the opposite of the meaning above.

I would expect `flex128` to set `int_type_is_encoded=true` (since the type **is** encoded in the value), and `native` to set ``int_type_is_encoded=false` (since the type **is not** encoded in the value).

File: src/mca/psquash/psquash.h [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+    pmix_psquash_base_module_finalize_fn_t finalize;
+
+    pmix_psquash_get_max_size_fn_t         get_max_size;
+
+    /** Integer compression */
+    pmix_psquash_encode_int_fn_t           encode_int;
+    pmix_psquash_decode_int_fn_t           decode_int;
+
+    /** Blob compression (i.e., modex) */
+    // JJH Todo
```
Comment (jjhursey) [inline src/mca/psquash/psquash.h]: You can remove this todo comment and the one above (lines 99 and 100). I'll follow up on it in a later PR.

File: src/mca/psquash/psquash.h (hunk 2 above)
Comment (artpol84) [reply src/mca/psquash/psquash.h]: @karasevb I agree with @jjhursey.
the name is confusing. Lets fix it as proposed.

File: src/mca/psquash/psquash.h (hunk 3 above)
Comment (karasevb) [reply src/mca/psquash/psquash.h]: Done with the latest force-pushed commit

File: src/mca/psquash/base/base.h (hunk 1 above)
Comment (karasevb) [reply src/mca/psquash/base/base.h]: I moved this macro because it is used only for `psquash` and is not used for `bfrops`, so there is no need to keep it in `bfrops`.

**Comment by karasevb** [comment]
Ready to go.

File: src/mca/psquash/base/base.h (hunk 1 above)
Comment (jjhursey) [reply src/mca/psquash/base/base.h]: That makes sense. Thanks

**Comment by artpol84** [comment]
@jjhursey are we good to merge?

**Comment by artpol84** [comment]
@rhc54 @jjhursey 
I recently discovered that flex128 packing is a well-known practice: 
https://en.m.wikipedia.org/wiki/Variable-length_quantity
In particular, our exact implementation matched Google Buffers zigzag encoding idea:
https://developers.google.com/protocol-buffers/docs/encoding#varints

This should not be a problem as it is BSD-licensed:
https://opensource.google.com/projects/protobuf

**Comment by artpol84** [comment]
Not surprising as the idea was quite simple.

**Comment by artpol84** [comment]
But the point is that as this encoding is widely used - it is safe to use it in PMIx
